export const GET_COURS_SUCCESS = "GET_COURS_SUCCESS"
export const GET_COURS_FAIL = "GET_COURS_FAIL"
export const GET_COURS_LOADING = "GET_COURS_LOADING"

//delete actionsTypes
export const DELETE_COURS_FAIL = "DELETE_COURS_FAIL"
export const DELETE_COURS_SUCCESS = "DELETE_COURS_SUCCESS"
//delete  teacher actionsTypes
export const DELETE_COURS_FAIL_TEACHER = "DELETE_COURS_FAIL_TEACHER"
export const DELETE_COURS_SUCCESS_TEACHER = "DELETE_COURS_SUCCESS_TEACHER"

//add cours actions types
export const ADD_COURS_FAIL = "ADD_COURS_FAIL"
export const ADD_COURS_SUCCESS = "ADD_COURS_SUCCESS"
//details cours actions types
export const GET_ONE_COURS_FAIL = "GET_ONE_COURS_FAIL"
export const GET_ONE_COURS_SUCCESS = "GET_ONE_COURS_SUCCESS"
//update cours actions types
export const UPDATE_ONE_COURS_FAIL = "UPDATE_ONE_COURS_FAIL"
export const UPDATE_ONE_COURS_SUCCESS = "UPDATE_ONE_COURS_SUCCESS"

//update cours teacher actions types
export const UPDATE_ONE_COURS_FAIL_TEACHER = "UPDATE_ONE_COURS_FAIL_TEACHER"
export const UPDATE_ONE_COURS_SUCCESS_TEACHER = "UPDATE_ONE_COURS_SUCCESS_TEACHER"
